{
 "title": "strudel-dash",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Current level of groooove", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Strudel BPM / CPM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "strudel_bpm", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Strudel BPM / CPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 1 },
   "targets": [
    { "expr": "strudel_bpm", "legendFormat": "__auto" }
   ]
  },
  { "title": "Users on platform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active / Inactive users",
   "type": "gauge",
   "description": "Number of active users\n\n**Type:** *gauge*\n\n",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(strudel_active_users{__ignore_usage__=\"\", })",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Active / Inactive users over time",
   "type": "timeseries",
   "description": "Number of active users\n\n**Type:** *gauge*\n\n",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(strudel_active_users{__ignore_usage__=\"\", })",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Other metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Strudel metric scrape duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Playback state",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 23 },
   "targets": [
    { "expr": "strudel_playback_state", "legendFormat": "__auto" }
   ]
  }
 ]
}