{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "strudel.fullname" . }}-grafana-datasources
  labels:
    {{- include "strudel.labels" . | nindent 4 }}
    component: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "strudel.fullname" . }}-prometheus:{{ .Values.prometheus.port }}
        isDefault: true
        editable: true
{{- end }}

