{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "strudel.fullname" . }}-grafana-dashboard
  labels:
    {{- include "strudel.labels" . | nindent 4 }}
    component: grafana
data:
  strudel-dashboard.json: |
    {{- .Files.Get "grafana-dashboard.json" | nindent 4 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "strudel.fullname" . }}-grafana
  labels:
    {{- include "strudel.labels" . | nindent 4 }}
    component: grafana
spec:
  replicas: 1  # Hardcoded to 1 since Grafana uses emptyDir storage (not shared between pods)
  selector:
    matchLabels:
      {{- include "strudel.selectorLabels" . | nindent 6 }}
      component: grafana
  template:
    metadata:
      labels:
        {{- include "strudel.selectorLabels" . | nindent 8 }}
        component: grafana
    spec:
      serviceAccountName: {{ include "strudel.serviceAccountName" . }}
      containers:
      - name: grafana
        image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
        imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.grafana.port }}
          protocol: TCP
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.grafana.existingSecret }}{{ .Values.grafana.existingSecret }}{{ else }}{{ include "strudel.fullname" . }}-grafana{{ end }}
              key: admin-user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.grafana.existingSecret }}{{ .Values.grafana.existingSecret }}{{ else }}{{ include "strudel.fullname" . }}-grafana{{ end }}
              key: admin-password
        - name: GF_INSTALL_PLUGINS
          value: ""
        - name: GF_PATHS_PROVISIONING
          value: "/etc/grafana/provisioning"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboard-provider
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-dashboard-config
          mountPath: /var/lib/grafana/dashboards
        {{- with .Values.grafana.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /api/health
            port: {{ .Values.grafana.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: {{ .Values.grafana.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-datasources
        configMap:
          name: {{ include "strudel.fullname" . }}-grafana-datasources
      - name: grafana-dashboard-provider
        configMap:
          name: {{ include "strudel.fullname" . }}-grafana-dashboard-provider
      - name: grafana-dashboard-config
        configMap:
          name: {{ include "strudel.fullname" . }}-grafana-dashboard

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "strudel.fullname" . }}-grafana
  labels:
    {{- include "strudel.labels" . | nindent 4 }}
    component: grafana
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.grafana.port }}
      targetPort: {{ .Values.grafana.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "strudel.selectorLabels" . | nindent 4 }}
    component: grafana
{{- end }}

